services:
  server1:
    platform: linux/amd64
    image: calvinl15/wui-auto-evaluate:v1.0.0
    shm_size: 2g
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - conda_env:/opt/conda/envs/wui-auto-eval
    command: /bin/sh -c "conda run --no-capture-output -n wui-auto-eval uvicorn server:app --host 0.0.0.0 --port ${PORT:-8000} --reload"

  server2:
    platform: linux/amd64
    image: calvinl15/wui-auto-evaluate:v1.0.0
    shm_size: 2g
    environment:
      - PORT=8001
    ports:
      - "8001:8001"
    volumes:
      - conda_env:/opt/conda/envs/wui-auto-eval
    command: /bin/sh -c "conda run --no-capture-output -n wui-auto-eval uvicorn server:app --host 0.0.0.0 --port ${PORT:-8001} --reload"

  server3:
    platform: linux/amd64
    image: calvinl15/wui-auto-evaluate:v1.0.0
    shm_size: 2g
    environment:
      - PORT=8002
    ports:
      - "8002:8002"
    volumes:
      - conda_env:/opt/conda/envs/wui-auto-eval
    command: /bin/sh -c "conda run --no-capture-output -n wui-auto-eval uvicorn server:app --host 0.0.0.0 --port ${PORT:-8002} --reload"

  server4:
    platform: linux/amd64
    image: calvinl15/wui-auto-evaluate:v1.0.0
    shm_size: 2g
    environment:
      - PORT=8003
    ports:
      - "8003:8003"
    volumes:
      - conda_env:/opt/conda/envs/wui-auto-eval
    command: /bin/sh -c "conda run --no-capture-output -n wui-auto-eval uvicorn server:app --host 0.0.0.0 --port ${PORT:-8003} --reload"

volumes:
  conda_env:
    external: false
